version: '3'

services:
  backend:
    build:
      context: ./backend
    restart: always
    environment:
      - PORT=8000
      - WEAVIATE_URL=${WEAVIATE_URL}
      - WEAVIATE_API_KEY=${WEAVIATE_API_KEY}
    expose:
      - "8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.prod
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
