name = "weaviatedemo"
compatibility_date = "2025-04-19"
pages_build_output_dir = "dist"

[site]
bucket = "./dist"

[env.production]
routes = [{pattern = "/api/*", forward = {service_binding = "backend"}}]

[env.development]
routes = [{pattern = "/api/*", forward = {service_binding = "backend"}}]
