name = "weaviatedemo"
compatibility_date = "2025-04-19"
pages_build_output_dir = "dist"

# Pages configuration
[pages]
dir = "dist"

# Routes configuration
[[routes]]
pattern = "/api/*"
forward = { service_binding = "backend" }
